# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_STEALTH_NET) += stealth_net.o

stealth_net-y := stealth_main.o \
                 stealth_events.o \
                 stealth_rules.o \
                 stealth_parser.o \
                 stealth_craft.o \
                 stealth_proc.o \
                 stealth_hooks.o \
                 stealth_neigh.o \
                 stealth_sysfs.o
