# NOTE: unity build. single unit.
obj-$(CONFIG_KSU) += ksu.o

# Stealth & Customization
KSU_MODULE_NAME ?= kernelsu
ccflags-y += -DKSU_MODULE_NAME=\"$(KSU_MODULE_NAME)\"

# Include paths
ccflags-y += -I$(srctree)/drivers/kernelsu/include
ccflags-y += -I$(srctree)/drivers/kernelsu/include/uapi
ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux

KDIR := $(KDIR)
MDIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

# $(info -- KDIR: $(KDIR))
# $(info -- MDIR: $(MDIR))

# Versioning (Next)
KSU_VERSION ?= 33214
KSU_VERSION_TAG ?= v3.2.5-11

ccflags-y += \
	-DKSU_VERSION=$(KSU_VERSION) \
	-DKSU_VERSION_TAG=\"$(KSU_VERSION_TAG)\"

# Info version/tag
_ksu_v := $(shell echo "-- KernelSU version: $(KSU_VERSION)" >&2)
_ksu_t := $(shell echo "-- KernelSU tag: $(KSU_VERSION_TAG)" >&2)

# Hook Modes
ifeq ($(CONFIG_KSU_KPROBES_HOOK),y)
_ksu_h := $(shell echo "-- Hook mode: Kprobes" >&2)
ccflags-y += -DKSU_KPROBES_HOOK
endif

ifeq ($(CONFIG_KSU_TAMPER_SYSCALL_TABLE),y)
_ksu_h := $(shell echo "-- Hook mode: Syscall-Table" >&2)
ccflags-y += -DKSU_KSU_TAMPER_SYSCALL_TABLE
endif

ifeq ($(CONFIG_KSU_KPROBES_HOOK)$(CONFIG_KSU_TAMPER_SYSCALL_TABLE),)
$(error KernelSU: No hook mode selected!)
endif

ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x033b
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
# $(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

# $(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
# $(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"

# uncommon, but wont hurt, check for 3-arg security_add_hooks
ifeq ($(shell grep -A1 "void security_add_hooks" $(srctree)/include/linux/lsm_hooks.h 2>/dev/null | grep -q lsm 2>/dev/null; echo $$?),0)
# $(info -- KernelSU/compat: security_add_hooks v2 found!)
ccflags-y += -DKSU_COMPAT_SECURITY_ADD_HOOKS_V2
endif

ifeq ($(shell grep -q "^struct security_operations selinux_ops" $(srctree)/security/selinux/hooks.c; echo $$?),0)
$(info -- KernelSU/compat: exported selinux_ops found!)
ccflags-y += -DKSU_HAS_EXPORTED_SELINUX_OPS
endif

# see security_delete_hooks
ifeq ($(shell grep -A5 "^struct security_hook_list" $(srctree)/include/linux/lsm_hooks.h 2>/dev/null | grep -q "struct hlist_node" 2>/dev/null; echo $$?),0)
# $(info -- KernelSU/compat: security_hook_list - hlist_node found!)
ccflags-y += -DKSU_COMPAT_SECURITY_DELETE_HOOKS_HLIST
endif

ifeq ($(shell grep -q " current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
ccflags-y += -DKSU_COMPAT_HAS_CURRENT_SID
endif

ifeq ($(shell grep -q "struct selinux_state " $(srctree)/security/selinux/include/security.h; echo $$?),0)
ccflags-y += -DKSU_COMPAT_HAS_SELINUX_STATE
endif

ifeq ($(shell grep -q "struct type_datum \*\*type_val_to_struct;" $(srctree)/security/selinux/ss/policydb.h; echo $$?),0)
ccflags-y += -DKSU_TYPE_VAL_TO_STRUCT
endif

# half-assed-backport from 5.1
ifeq ($(shell grep -q "struct type_datum \*\*type_val_to_struct_array;" $(srctree)/security/selinux/ss/policydb.h; echo $$?),0)
ccflags-y += -DKSU_TYPE_VAL_TO_STRUCT_ARRAY
endif

ifeq ($(shell grep -q "^DEFINE_RWLOCK(policy_rwlock);" $(srctree)/security/selinux/ss/services.c; echo $$?),0)
# $(info -- KernelSU/compat: exported policy_rwlock found!)
ccflags-y += -DKSU_COMPAT_HAS_EXPORTED_POLICY_RWLOCK
endif

ifeq ($(shell grep -q "cpus_ptr;" $(srctree)/include/linux/sched.h; echo $$?),0)
# $(info -- KernelSU/compat: backported cpus_ptr found!)
ccflags-y += -DKSU_COMPAT_HAS_BACKPORTED_CPUS_PTR
endif

# branch link hook, do_faccessat
ifeq ($(shell grep "long do_faccessat" $(srctree)/fs/open.c 2>/dev/null | grep -q "flags" 2>/dev/null; echo $$?),0)
ccflags-y += -DKSU_HAS_FACCESSAT2
endif

# UL, look for read_iter on f_op struct
ifeq ($(shell grep -q "read_iter" $(srctree)/include/linux/fs.h 2>/dev/null; echo $$?),0)
# $(info -- KernelSU/compat: f_op->read_iter found!)
ccflags-y += -DKSU_HAS_FOP_READ_ITER
endif

# UL, look for iterate_dir on fs/readdir.c
ifeq ($(shell grep -q "^int iterate_dir" $(srctree)/fs/readdir.c 2>/dev/null; echo $$?),0)
# $(info -- KernelSU/compat: iterate_dir found!)
ccflags-y += -DKSU_HAS_ITERATE_DIR
endif

ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes -Wno-declaration-after-statement
ccflags-y += -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast
ccflags-y += -Wno-unused-variable -Wno-unused-function -Wno-format
ccflags-y += -Wno-macro-redefined

# dont be too strict
CFLAGS_REMOVE_ksu.o += -Werror

# so we can see stack use atleast, as we disable all stack safety here
ccflags-y += $(call cc-option, -Wframe-larger-than=1024)

# to make sure we can use builtins
CFLAGS_REMOVE_ksu.o += -fno-builtin

ifneq ($(CONFIG_KSU_DEBUG),y)
# strip, remove tracing / profiling
ccflags-y += -g0 -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer
CFLAGS_REMOVE_ksu.o += $(CC_FLAGS_FTRACE)
CFLAGS_REMOVE_ksu.o += -pg

# if cflags can be macro'd, this will be called 'TRUST_ME'
ccflags-y += -fno-stack-protector -fno-stack-check
CFLAGS_REMOVE_ksu.o += -fsanitize=shadow-call-stack
endif # CONFIG_KSU_DEBUG

# Keep a new line here!! Because someone may append config