name: Nethunter

on:
  push:
    branches:
      - nethunter  # Trigger only on nethunter branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make compile.sh executable
        run: chmod +x ./Levion_kernel_OP9/compile.sh

      - name: Run compile.sh
        run: |
          cd ./Levion_kernel_OP9
          ./compile.sh

      - name: Find generated zip
        id: zip
        run: |
          FILE=$(ls $HOME/op9/*.zip | head -n 1)
          echo "zip_file=$FILE" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: Nethunter
          release_name: Nethunter
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.zip_file }}
          asset_name: ${{ env.zip_file | split('/')[-1] }}
          asset_content_type: application/zip